ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/main.d -of=o-elf-x86_64/main.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/bootloader/limine.d -of=o-elf-x86_64/bootloader/limine.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/core/mem.d -of=o-elf-x86_64/core/mem.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/core/vga.d -of=o-elf-x86_64/core/vga.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/core/ps2.d -of=o-elf-x86_64/core/ps2.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/core/keyboard.d -of=o-elf-x86_64/core/keyboard.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/core/pit.d -of=o-elf-x86_64/core/pit.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/core/pci.d -of=o-elf-x86_64/core/pci.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/core/framebuffer.d -of=o-elf-x86_64/core/framebuffer.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/core/paging.d -of=o-elf-x86_64/core/paging.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/logo.d -of=o-elf-x86_64/logo.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/cursor.d -of=o-elf-x86_64/cursor.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/font.d -of=o-elf-x86_64/font.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/console.d -of=o-elf-x86_64/console.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/stdio.d -of=o-elf-x86_64/stdio.o
ldc2 -c -betterC -I=src -mtriple=x86_64-none-elf -release -nodefaultlib --boundscheck=off --disable-red-zone --use-ctors=0 --fno-exceptions --nogc -code-model=medium -O0 src/error.d -of=o-elf-x86_64/error.o
nasm -f elf64 -o o-elf-x86_64/port64.s.o src/port64.s
nasm -f elf64 -o o-elf-x86_64/core/mem.s.o src/core/mem.s
ld.lld -m elf_x86_64 -T linker64.ld -z max-page-size=0x1000 -static --gc-sections -nostdlib -o cdroot64/kernel64.bin o-elf-x86_64/main.o o-elf-x86_64/bootloader/limine.o o-elf-x86_64/port64.s.o o-elf-x86_64/core/mem.s.o o-elf-x86_64/core/mem.o o-elf-x86_64/core/vga.o o-elf-x86_64/core/ps2.o o-elf-x86_64/core/keyboard.o o-elf-x86_64/core/pci.o o-elf-x86_64/core/pit.o o-elf-x86_64/core/framebuffer.o o-elf-x86_64/core/paging.o o-elf-x86_64/logo.o o-elf-x86_64/cursor.o o-elf-x86_64/font.o o-elf-x86_64/console.o o-elf-x86_64/stdio.o o-elf-x86_64/error.o
xorriso -as mkisofs -r -b limine/limine-bios-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e limine/limine-uefi-cd.bin -no-emul-boot --efi-boot-part --efi-boot-image --protective-msdos-label -o dios64.iso ./cdroot64
